---
apiVersion: v1
kind: Service
metadata:
  name: trigger
spec:
  type: ClusterIP
  selector:
    app: trigger
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  - name: https
    port: 8100
    targetPort: 8443
