---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqconsume
  labels:
    app: mqconsume
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mqconsume
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqconsume
    spec:
      containers:
      - name: mqconsume
        image: mqconsume:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: mqconsume-env
      terminationGracePeriodSeconds: 180