resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mqconsume-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
    - AzureFunctionsJobHost__telemetryMode=OpenTelemetry
    - AzureWebJobsStorage__blobServiceUri={funcstoragefeed4.outputs.blobEndpoint}
    - AzureWebJobsStorage__queueServiceUri={funcstoragefeed4.outputs.queueEndpoint}
    - AzureWebJobsStorage__tableServiceUri={funcstoragefeed4.outputs.tableEndpoint}
    - Aspire__Azure__Storage__Blobs__AzureWebJobsStorage__ServiceUri={funcstoragefeed4.outputs.blobEndpoint}
    - Aspire__Azure__Storage__Queues__AzureWebJobsStorage__ServiceUri={funcstoragefeed4.outputs.queueEndpoint}
    - Aspire__Azure__Data__Tables__AzureWebJobsStorage__ServiceUri={funcstoragefeed4.outputs.tableEndpoint}
    - ConnectionStrings__rabbitmq=amqp://guest:VFBKPRhTEa9JpwdseqxS4L@rabbitmq:5672
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=mqconsume
    - ASPNETCORE_URLS=http://+:8080;

